name: Build Exercises on Ubuntu

on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - '**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install g++-9 for C++98 support
        run: |
          sudo apt-get update
          sudo apt-get install -y g++-9
          export CXX=g++-9

      - name: Build each exercise directory
        run: |
          for dir in ex*/; do
            if [ -f "$dir/Makefile" ]; then
              echo "Building in $dir..."
              make -C "$dir" || exit 1
            else
              echo "Warning: No Makefile found in $dir"
            fi
          done